### ISSUE TITLE
firestore の設計相談

### ISSUE THREAD

**Issue by Rei-Sogawa** [hirocueki/hiden-note#99]
- notes (top level collection)
  - userId
  - createdAt
  - tags
  - latestHistory (history doc と同じ構造で)
  - histories (sub collection)
    - userId
    - createdAt
    - title
    - content
  - comments (sub collection)
    - userId
    - createdAt
    - content

firestore の構造は上のようにしませんか？？
ノート作成・更新の際は notes の latestHistory だけ気にして、sub collection の histories には cloud function firestore trigger を使って latestHistory と全く同じのを追加していきましょう
tags だけの変更かどうかも、そこででチェックして tags だけであれば histories へは追加しないようにして
あと、今は comments に noteId フィールドもありそうですけど note の sub collection だからいらない？

**Comment by hirocueki** [comment]
> comments に noteId フィールドもありそうですけど note の sub collection だからいらない？

これは不要そうですね

**Comment by hirocueki** [comment]
> histories には cloud function firestore trigger を使って latestHistory と全く同じのを追加していきましょう

latestHistoryがhistory docとまったくおなじデータなのであれば、
最新のhistoriesがlatestHistoryとできないかなーとおもいました。

新規作成は noteが1つできて、historiesが1つ増える。
更新は、既存のnoteのhistoriesが1つ増える。みたいな。

考慮漏れがありそうだけど、データをupdateすることが減ったほうがよさそうにおもった

**Comment by Rei-Sogawa** [comment]
latestHistory は非正規化して、note に持たせた方がいいかなと思いました。
非正規化することによって同期を取る必要があるものは cloud function で処理するのがいいのかなと。
